### PR TITLE
Es 6 classes

### PR DESCRIPTION
**Pull request by husush23**
In Project I :
Switched all JavaScript functionalities into ES6 classes
Edited some files

### CODE REVIEW

**Review by 1GORDON — COMMENTED** [review]
##
## Hi @husush23 & @AleWaweru ✋

Good job so far!

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

### This project will be marked as Invalid and won't affect the number of your weekly reviews

- [ ] Kindly remove all the code that disables linter checks. Linter checks help us write more professional code.
- [ ] Kindly remove the Microverse logo from your readme file and you may optionally replace it with your own logo if you have one.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by husush23** [comment]
@1GORDON  I don't know if you are aware of the curriculum or not but I'll recommend you check project requirements and everything before marking invalid to my project. that code I used to disable linters is recommended on the exercise page of the lesson check that and check the details there.  below is the screenshot of it

Screenshot 2023-05-03 171925

**Comment by prolajumokeoni** [comment]
Hi @husush23, this exception was pointed out for plain objects milestone, it is possible the previous reviewer did not see this exception, well-done pointing that out 👍🏿

**Review by prolajumokeoni — APPROVED** [review]
Hi @husush23 and @AleWaweru 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 
 - Refactored to use javascript classes ✅


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- Kindly ensure that as partners you always have balanced commits in a pair programming project 👍 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
